import { MongoRepository } from './MongoRepository.js';
import {
  Employee,
  Project,
  Task,
  Timesheet,
  Budget,
  Department,
  Skill,
  Notification,
  AuditLog,
  Risk,
  Issue,
  Leave,
  Attendance,
  Document,
  PcpRequest,
  PcpRevision,
  PcpUser,
  PcpApprovalChain,
  PcpMasterConfig,
} from '../models/index.js';

export const repos = {
  employees: new MongoRepository(Employee),
  projects: new MongoRepository(Project),
  tasks: new MongoRepository(Task),
  timesheets: new MongoRepository(Timesheet),
  budgets: new MongoRepository(Budget),
  departments: new MongoRepository(Department),
  skills: new MongoRepository(Skill),
  notifications: new MongoRepository(Notification),
  auditlogs: new MongoRepository(AuditLog),
  risks: new MongoRepository(Risk),
  issues: new MongoRepository(Issue),
  leaves: new MongoRepository(Leave),
  attendance: new MongoRepository(Attendance),
  documents: new MongoRepository(Document),
  pcpRequests: new MongoRepository(PcpRequest),
  pcpRevisions: new MongoRepository(PcpRevision),
  pcpUsers: new MongoRepository(PcpUser),
  pcpApprovalChains: new MongoRepository(PcpApprovalChain),
  pcpMasterConfig: new MongoRepository(PcpMasterConfig),
};
