import { v4 as uuidv4 } from 'uuid';
import { repos } from '../repositories/index.js';

const LATE_AFTER_HOUR = 9;
const AUTO_ABSENT_AFTER_HOUR = 10;
const AUTO_ABSENT_AFTER_MINUTE = 30;

function dateOnly(d = new Date()) {
  return d.toISOString().slice(0, 10);
}

function calcWorkHours(checkIn, checkOut) {
  if (!checkIn || !checkOut) return 0;
  const [inH, inM] = checkIn.split(':').map(Number);
  const [outH, outM] = checkOut.split(':').map(Number);
  const mins = (outH * 60 + outM) - (inH * 60 + inM);
  return Math.max(0, Math.round((mins / 60) * 10) / 10);
}

function formatTime(date) {
  return `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
}

export function isWeekday(dateStr) {
  const day = new Date(`${dateStr}T12:00:00`).getDay();
  return day !== 0 && day !== 6;
}

function isOnApprovedLeave(employeeId, dateStr, leaves) {
  return leaves.some(
    (l) =>
      l.employeeId === employeeId
      && l.status === 'Approved'
      && dateStr >= l.startDate
      && dateStr <= l.endDate,
  );
}

export function shouldApplyAutoAbsent(dateStr, now = new Date()) {
  if (!isWeekday(dateStr)) return false;
  const today = dateOnly(now);
  if (dateStr < today) return true;
  if (dateStr > today) return false;
  const mins = now.getHours() * 60 + now.getMinutes();
  return mins >= AUTO_ABSENT_AFTER_HOUR * 60 + AUTO_ABSENT_AFTER_MINUTE;
}

export async function applyAutoAbsentForDate(dateStr) {
  if (!shouldApplyAutoAbsent(dateStr)) return [];

  const [employees, attendance, leaves] = await Promise.all([
    repos.employees.getAll(),
    repos.attendance.getAll(),
    repos.leaves.getAll(),
  ]);

  const created = [];
  const activeEmployees = employees.filter((e) => e.active !== false);

  for (const emp of activeEmployees) {
    const existing = attendance.find((a) => a.employeeId === emp.id && a.date === dateStr);
    if (existing && !existing.autoGenerated) continue;

    if (isOnApprovedLeave(emp.id, dateStr, leaves)) {
      if (existing?.status === 'On Leave') continue;
      const record = {
        employeeId: emp.id,
        date: dateStr,
        status: 'On Leave',
        notes: 'Auto-marked (approved leave)',
        autoGenerated: true,
        approvalStatus: 'Accepted',
      };
      if (existing) {
        await repos.attendance.update(existing.id, { ...record, updatedAt: new Date().toISOString() });
        created.push({ ...existing, ...record });
      } else {
        const item = {
          id: uuidv4(),
          ...record,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        await repos.attendance.create(item);
        created.push(item);
      }
      continue;
    }

    if (existing) continue;

    const record = {
      id: uuidv4(),
      employeeId: emp.id,
      date: dateStr,
      status: 'Absent',
      notes: 'Auto-marked absent (no check-in)',
      autoGenerated: true,
      approvalStatus: 'Accepted',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    await repos.attendance.create(record);
    created.push(record);
  }

  return created;
}

export async function listAttendance({ date, employeeId, applyAutoAbsent = false } = {}) {
  if (date && applyAutoAbsent !== false && applyAutoAbsent !== 'false') {
    await applyAutoAbsentForDate(date);
  }

  let records = await repos.attendance.getAll();
  if (date) records = records.filter((r) => r.date === date);
  if (employeeId) records = records.filter((r) => r.employeeId === employeeId);

  return records.sort(
    (a, b) => b.date.localeCompare(a.date) || a.employeeId.localeCompare(b.employeeId),
  );
}

export async function getTodayAttendance(employeeId) {
  const today = dateOnly();
  if (shouldApplyAutoAbsent(today)) {
    await applyAutoAbsentForDate(today);
  }
  const all = await repos.attendance.getAll();
  return all.find((a) => a.employeeId === employeeId && a.date === today) || null;
}

export async function selfCheckIn(employeeId, { location = 'Site' } = {}) {
  const now = new Date();
  const today = dateOnly(now);

  if (!isWeekday(today)) {
    throw new Error('Check-in is only available on weekdays');
  }

  const all = await repos.attendance.getAll();
  const leaves = await repos.leaves.getAll();
  const existing = all.find((a) => a.employeeId === employeeId && a.date === today);

  if (isOnApprovedLeave(employeeId, today, leaves)) {
    throw new Error('You are on approved leave today');
  }

  if (existing && !existing.autoGenerated && existing.checkIn) {
    throw new Error('You have already checked in for today');
  }

  const timeStr = formatTime(now);
  const mins = now.getHours() * 60 + now.getMinutes();
  const status = mins > LATE_AFTER_HOUR * 60 ? 'Late' : 'Present';

  const payload = {
    employeeId,
    date: today,
    checkIn: timeStr,
    checkOut: existing?.checkOut,
    status,
    location,
    workHours: existing?.checkOut ? calcWorkHours(timeStr, existing.checkOut) : (existing?.workHours || 0),
    notes: existing?.autoGenerated ? 'Checked in after auto-absent window' : '',
    autoGenerated: false,
    approvalStatus: 'Pending',
    recordedBy: employeeId,
    updatedAt: new Date().toISOString(),
  };

  if (existing) {
    return repos.attendance.update(existing.id, payload);
  }

  return repos.attendance.create({
    id: uuidv4(),
    ...payload,
    createdAt: new Date().toISOString(),
  });
}

export async function selfCheckOut(employeeId) {
  const now = new Date();
  const today = dateOnly(now);

  if (!isWeekday(today)) {
    throw new Error('Check-out is only available on weekdays');
  }

  const all = await repos.attendance.getAll();
  const existing = all.find((a) => a.employeeId === employeeId && a.date === today);

  if (!existing?.checkIn) {
    throw new Error('You must check in before checking out');
  }
  if (existing.checkOut) {
    throw new Error('You have already checked out for today');
  }

  const timeStr = formatTime(now);
  const workHours = calcWorkHours(existing.checkIn, timeStr);

  return repos.attendance.update(existing.id, {
    checkOut: timeStr,
    workHours,
    approvalStatus: 'Pending',
    autoGenerated: false,
    updatedAt: new Date().toISOString(),
  });
}

export async function acceptAttendance(id, acceptedBy) {
  const existing = await repos.attendance.getById(id);
  if (!existing) throw new Error('Attendance record not found');
  if (existing.approvalStatus === 'Accepted') {
    throw new Error('Attendance already accepted');
  }
  if (
    !existing.autoGenerated
    && existing.status !== 'Absent'
    && existing.status !== 'On Leave'
    && !existing.checkOut
  ) {
    throw new Error('Employee must check out before attendance can be accepted');
  }

  return repos.attendance.update(id, {
    approvalStatus: 'Accepted',
    acceptedBy,
    acceptedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  });
}

export async function validateAttendance(data, existingId) {
  const errors = [];
  if (!data.employeeId) errors.push('Employee is required');
  if (!data.date) errors.push('Date is required');
  if (!data.status) errors.push('Status is required');
  if (data.employeeId && data.date) {
    const all = await repos.attendance.getAll();
    const dup = all.find(
      (a) => a.employeeId === data.employeeId && a.date === data.date && a.id !== existingId,
    );
    if (dup) errors.push('Attendance already recorded for this employee on this date');
  }
  return errors;
}
