import { Router } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { repos } from '../repositories/index.js';
import { logAudit } from '../services/auditService.js';
import { createNotification } from '../services/notificationService.js';
import { verifyAuthToken } from '../services/authService.js';
import {
  listAttendance,
  getTodayAttendance,
  selfCheckIn,
  selfCheckOut,
  acceptAttendance,
  validateAttendance,
} from '../services/attendanceService.js';

const router = Router();

function sanitizeBody(body) {
  const { id, createdAt, updatedAt, ...rest } = body;
  return rest;
}

function requireAuth(req, res, next) {
  const header = req.headers.authorization || '';
  const token = header.startsWith('Bearer ') ? header.slice(7) : null;
  if (!token) return res.status(401).json({ error: 'Not authenticated' });
  try {
    req.auth = verifyAuthToken(token);
    next();
  } catch {
    res.status(401).json({ error: 'Invalid or expired session' });
  }
}

function requireAttendanceManager(req, res, next) {
  const role = req.auth?.systemRole;
  if (role !== 'Admin' && role !== 'HR') {
    return res.status(403).json({ error: 'Only Admin or HR can manage attendance' });
  }
  next();
}

router.get('/', async (req, res) => {
  try {
    const { date, employeeId, applyAutoAbsent } = req.query;
    const records = await listAttendance({
      date: date || undefined,
      employeeId: employeeId || undefined,
      applyAutoAbsent: applyAutoAbsent !== 'false',
    });
    res.json(records);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/today', requireAuth, async (req, res) => {
  try {
    const record = await getTodayAttendance(req.auth.sub);
    res.json({ record });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/check-in', requireAuth, async (req, res) => {
  try {
    const record = await selfCheckIn(req.auth.sub, {
      location: req.body?.location || 'Site',
    });
    res.status(201).json(record);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/check-out', requireAuth, async (req, res) => {
  try {
    const record = await selfCheckOut(req.auth.sub);
    res.json(record);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/:id/accept', requireAuth, requireAttendanceManager, async (req, res) => {
  try {
    const record = await acceptAttendance(req.params.id, req.auth.sub);
    await logAudit('UPDATE', 'Attendance', req.params.id, 'Attendance accepted');
    res.json(record);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.get('/:id', async (req, res) => {
  try {
    const item = await repos.attendance.getById(req.params.id);
    if (!item) return res.status(404).json({ error: 'Not found' });
    res.json(item);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/', requireAuth, requireAttendanceManager, async (req, res) => {
  try {
    const errors = await validateAttendance(req.body);
    if (errors.length) return res.status(400).json({ error: errors.join('; ') });

    const item = {
      id: uuidv4(),
      ...sanitizeBody(req.body),
      autoGenerated: false,
      approvalStatus: 'Accepted',
      acceptedBy: req.auth.sub,
      acceptedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    await repos.attendance.create(item);
    await logAudit('CREATE', 'Attendance', item.id, `Attendance created for ${item.date}`);

    if (item.status === 'Absent' || item.status === 'Late') {
      const emp = await repos.employees.getById(item.employeeId);
      if (emp) {
        await createNotification(
          'attendance',
          item.status === 'Absent' ? 'Absence Recorded' : 'Late Arrival',
          `${emp.fullName} marked ${item.status.toLowerCase()} on ${item.date}`,
          'all',
        );
      }
    }

    res.status(201).json(item);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.put('/:id', requireAuth, requireAttendanceManager, async (req, res) => {
  try {
    const existing = await repos.attendance.getById(req.params.id);
    if (!existing) return res.status(404).json({ error: 'Not found' });

    const errors = await validateAttendance({ ...existing, ...req.body }, req.params.id);
    if (errors.length) return res.status(400).json({ error: errors.join('; ') });

    const updates = {
      ...sanitizeBody(req.body),
      autoGenerated: false,
      approvalStatus: 'Accepted',
      acceptedBy: req.auth.sub,
      acceptedAt: new Date().toISOString(),
    };
    const updated = await repos.attendance.update(req.params.id, updates);
    await logAudit('UPDATE', 'Attendance', req.params.id, 'Attendance updated');
    res.json(updated);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/:id', requireAuth, requireAttendanceManager, async (req, res) => {
  try {
    const existing = await repos.attendance.getById(req.params.id);
    if (!existing) return res.status(404).json({ error: 'Not found' });
    await repos.attendance.delete(req.params.id);
    await logAudit('DELETE', 'Attendance', req.params.id, 'Attendance deleted');
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
