export const pcpMasters = {
  clients: ['ADNOC Refinery Electrical Turnaround', 'Ruwais Piping & Welding Package', 'Ruwais MEP Campus Build'],
  locations: ['Abu Dhabi', 'Dubai', 'Ruwais', 'Other'],
  recruitmentTypes: ['New Hire', 'Replacement', 'Transfer', 'Re-hire', 'Contract Extension'],
  businessUnits: ['Construction – North', 'MEP – East', 'Corporate HR', 'Logistics – South'],
  wbsByBu: {
    'Construction – North': ['W95-ENG-01', 'W95-HR-02'],
    'MEP – East': ['W95-EL-01', 'W95-MEP-03'],
    'Corporate HR': ['W95-HR-02', 'W95-ADM-01'],
    'Logistics – South': ['W95-LOG-01', 'W95-ENG-01'],
  },
  priorities: ['Normal', 'Urgent', 'Critical'],
  positionTitles: ['Site Engineer', 'Safety Officer', 'HR Officer', 'Electrician', 'Logistics Coordinator', 'Welder', 'Rigger'],
  jobFamilies: ['Engineering', 'HSE', 'Human Resources', 'Electrical', 'Logistics'],
  grades: [
    { code: 'B1', bandMin: 8000, bandMax: 12000 },
    { code: 'B2', bandMin: 10000, bandMax: 15000 },
    { code: 'B3', bandMin: 12000, bandMax: 18000 },
    { code: 'C5', bandMin: 6000, bandMax: 9000 },
  ],
  employmentTypes: ['Permanent', 'Fixed-Term Contract', 'Secondment'],
  shifts: ['Day', 'Night', 'Rotational'],
  workLocations: ['Site', 'Camp', 'Head Office', 'Client Premises'],
  contractDurations: ['6', '12', '24', '36', 'Open-ended'],
  noticePeriods: ['30', '60', '90'],
  probationPeriods: ['3', '6'],
  benefits: ['Housing', 'Transport', 'Medical', 'Air Tickets', 'Annual Leaves', 'Insurance', 'Visa/Iqama', 'Other'],
  costCenters: [
    { code: 'CC305', name: 'Construction Ops' },
    { code: 'CC103', name: 'MEP Services' },
    { code: 'CC104', name: 'Logistics' },
    { code: 'CC106', name: 'Electrical' },
    { code: 'CC201', name: 'Corporate HR' },
  ],
  reportingLines: ['Bilal Ahmed – Construction Manager', 'Saira Malik – HSE Lead', 'Hassan Raza – HR Director'],
};

export const pcpApprovalChains = [
  {
    id: 'chain-1',
    businessUnit: 'Construction – North',
    gradeMin: 'B1',
    gradeMax: 'B3',
    budgetThreshold: 500000,
    steps: ['BU Head', 'Finance Manager', 'HR Director'],
  },
  {
    id: 'chain-2',
    businessUnit: 'MEP – East',
    gradeMin: 'B1',
    gradeMax: 'C5',
    budgetThreshold: 300000,
    steps: ['BU Head', 'Finance Manager'],
  },
];

const benefitAmount = (name, amount) => ({ name, amount });

export const pcpRequests = [
  {
    id: 'pcp-1',
    pcpNo: 'PCP-2026-00041',
    client: 'ADNOC Refinery Electrical Turnaround',
    clientLocation: 'Abu Dhabi',
    recruitmentType: 'New Hire',
    issueDate: '2026-06-02',
    requiredByDate: '2026-07-15',
    businessUnit: 'Construction – North',
    wbs: 'W95-ENG-01',
    priority: 'Critical',
    requestedBy: 'Muhammad Imran',
    requestedById: 'emp-1',
    status: 'In Approval',
    currentStage: 'Finance Manager',
    revision: 2,
    slaHoursRemaining: 14,
    slaOverdue: false,
    sapSync: 'Not Connected',
    approvalTrail: [
      { step: 'Submitted', by: 'Muhammad Imran', at: '2026-06-02T09:00:00Z', tatHours: null },
      { step: 'Approved', by: 'BU Head (Fatima Bukhari)', at: '2026-06-03T18:00:00Z', tatHours: 9 },
      { step: 'Pending', by: 'Finance Manager', at: null, slaDue: '2026-06-05T18:00:00Z' },
    ],
    positions: [
      {
        id: 'pos-1',
        title: 'Electrician',
        jobFamily: 'Electrical',
        grade: 'B2',
        count: 2,
        employmentType: 'Fixed-Term Contract',
        shift: 'Night',
        workLocation: 'Site',
        plannedStart: '2026-08-01',
        plannedDemob: '2027-08-01',
        reportingLine: 'Bilal Ahmed – Construction Manager',
        marketSalary: 12000,
        proposedSalary: 12500,
        salaryOnHired: null,
        benefits: [benefitAmount('Housing', 2000), benefitAmount('Transport', 800), benefitAmount('Medical', 500)],
        contractDuration: '12',
        noticePeriod: '30',
        probationPeriod: '3',
        costCenters: [{ code: 'CC305', percent: 60 }, { code: 'CC103', percent: 40 }],
        bandBreachJustification: 'Night shift premium required for site availability',
        monthlyBudget: 17200,
        totalBudget: 206400,
        actualCost: null,
        filled: 1,
        vacant: 1,
        daysVacant: 48,
      },
      {
        id: 'pos-2',
        title: 'Site Engineer',
        jobFamily: 'Engineering',
        grade: 'B3',
        count: 1,
        employmentType: 'Permanent',
        shift: 'Day',
        workLocation: 'Site',
        plannedStart: '2026-09-01',
        plannedDemob: null,
        reportingLine: 'Bilal Ahmed – Construction Manager',
        marketSalary: 15000,
        proposedSalary: 14800,
        benefits: [benefitAmount('Housing', 2500), benefitAmount('Medical', 600)],
        contractDuration: 'Open-ended',
        noticePeriod: '60',
        probationPeriod: '6',
        costCenters: [{ code: 'CC305', percent: 100 }],
        monthlyBudget: 17900,
        totalBudget: 214800,
        actualCost: 17100,
        filled: 1,
        vacant: 0,
        daysVacant: 0,
      },
    ],
    monthlyTotal: 35100,
    annualTotal: 421200,
    budgetVsActual: -4.2,
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-03T18:00:00Z',
  },
  {
    id: 'pcp-2',
    pcpNo: 'PCP-2026-00038',
    client: 'Ruwais Piping & Welding Package',
    clientLocation: 'Ruwais',
    recruitmentType: 'Replacement',
    issueDate: '2026-05-20',
    requiredByDate: '2026-06-30',
    businessUnit: 'MEP – East',
    wbs: 'W95-EL-01',
    priority: 'Urgent',
    requestedBy: 'Muhammad Imran',
    requestedById: 'emp-1',
    status: 'Approved',
    currentStage: 'Closed',
    revision: 1,
    slaHoursRemaining: 0,
    sapSync: 'Not Connected',
    approvalTrail: [
      { step: 'Submitted', by: 'Muhammad Imran', at: '2026-05-20T08:00:00Z' },
      { step: 'Approved', by: 'BU Head', at: '2026-05-21T12:00:00Z', tatHours: 28 },
      { step: 'Approved', by: 'Finance Manager', at: '2026-05-22T10:00:00Z', tatHours: 22 },
    ],
    positions: [
      {
        id: 'pos-3',
        title: 'Welder',
        jobFamily: 'Engineering',
        grade: 'C5',
        count: 6,
        employmentType: 'Fixed-Term Contract',
        shift: 'Day',
        workLocation: 'Site',
        plannedStart: '2026-09-01',
        marketSalary: 7500,
        proposedSalary: 7800,
        benefits: [benefitAmount('Transport', 500)],
        contractDuration: '12',
        noticePeriod: '30',
        costCenters: [{ code: 'CC106', percent: 100 }],
        monthlyBudget: 49800,
        totalBudget: 597600,
        filled: 0,
        vacant: 6,
        daysVacant: 22,
      },
    ],
    monthlyTotal: 49800,
    annualTotal: 597600,
    budgetVsActual: 6.8,
    createdAt: '2026-05-20T08:00:00Z',
    updatedAt: '2026-05-22T10:00:00Z',
  },
  {
    id: 'pcp-3',
    pcpNo: 'PCP-2026-00035',
    client: 'ADNOC Refinery Electrical Turnaround',
    clientLocation: 'Dubai',
    recruitmentType: 'New Hire',
    issueDate: '2026-05-10',
    requiredByDate: '2026-06-15',
    businessUnit: 'Construction – North',
    wbs: 'W95-ENG-01',
    priority: 'Normal',
    requestedBy: 'Muhammad Imran',
    requestedById: 'emp-1',
    status: 'Draft',
    currentStage: 'Draft',
    revision: 0,
    sapSync: 'Not Connected',
    approvalTrail: [],
    positions: [
      {
        id: 'pos-4',
        title: 'Safety Officer',
        jobFamily: 'HSE',
        grade: 'B2',
        count: 1,
        employmentType: 'Permanent',
        shift: 'Day',
        workLocation: 'Site',
        plannedStart: '2026-07-01',
        marketSalary: 11000,
        proposedSalary: 11200,
        benefits: [benefitAmount('Medical', 500)],
        contractDuration: 'Open-ended',
        noticePeriod: '30',
        costCenters: [{ code: 'CC305', percent: 100 }],
        monthlyBudget: 11700,
        totalBudget: 140400,
        filled: 0,
        vacant: 1,
        daysVacant: 0,
      },
    ],
    monthlyTotal: 11700,
    annualTotal: 140400,
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-05-10T08:00:00Z',
  },
];

export const pcpRevisions = [
  {
    id: 'rev-1-0',
    pcpId: 'pcp-1',
    revision: 0,
    author: 'Muhammad Imran',
    date: '2026-06-02',
    status: 'Superseded',
    summary: 'Original submission: 2 Electricians (Day shift), 1 Site Engineer.',
    snapshot: {
      monthlyTotal: 34300,
      headcount: 3,
      positions: [
        { title: 'Electrician', shift: 'Day', count: 2, monthlyBudget: 16400, costCenters: 'CC305 60% / CC103 40%' },
        { title: 'Site Engineer', shift: 'Day', count: 1, monthlyBudget: 17900, costCenters: 'CC305 100%' },
      ],
    },
  },
  {
    id: 'rev-1-1',
    pcpId: 'pcp-1',
    revision: 1,
    author: 'Muhammad Imran',
    date: '2026-06-02',
    status: 'Approved',
    justification: 'Added night-shift allowance per site requirements.',
    summary: 'Rev. 1: Shift changed Day → Night for Electrician; night-shift allowance added AED 800/month.',
    changes: [
      { field: 'Shift', position: 'Electrician', oldValue: 'Day', newValue: 'Night' },
      { field: 'Monthly Cost', position: 'Electrician', oldValue: '16400', newValue: '17200' },
      { field: 'Band Breach', position: 'Electrician', oldValue: 'None', newValue: 'Night shift premium justification added' },
    ],
    snapshot: {
      monthlyTotal: 35100,
      headcount: 3,
      positions: [
        { title: 'Electrician', shift: 'Night', count: 2, monthlyBudget: 17200, costCenters: 'CC305 60% / CC103 40%' },
        { title: 'Site Engineer', shift: 'Day', count: 1, monthlyBudget: 17900, costCenters: 'CC305 100%' },
      ],
    },
  },
  {
    id: 'rev-1-2',
    pcpId: 'pcp-1',
    revision: 2,
    author: 'Muhammad Imran',
    date: '2026-06-03',
    status: 'In Approval',
    justification: 'Cost center reallocation per finance guidance.',
    summary: 'Rev. 2: Cost Center 2 reallocated CC103 → CC106; charging balanced.',
    changes: [
      { field: 'Cost Center 2', position: 'Electrician', oldValue: 'CC103 (40%)', newValue: 'CC106 (40%)' },
      { field: 'Charging', position: 'Electrician', oldValue: 'CC305 60% / CC103 40%', newValue: 'CC305 60% / CC106 40%' },
    ],
    snapshot: {
      monthlyTotal: 35100,
      headcount: 3,
      positions: [
        { title: 'Electrician', shift: 'Night', count: 2, monthlyBudget: 17200, costCenters: 'CC305 60% / CC106 40%' },
        { title: 'Site Engineer', shift: 'Day', count: 1, monthlyBudget: 17900, costCenters: 'CC305 100%' },
      ],
    },
  },
  {
    id: 'rev-2-0',
    pcpId: 'pcp-2',
    revision: 0,
    author: 'Muhammad Imran',
    date: '2026-05-20',
    status: 'Superseded',
    summary: 'Initial request: 4 Welders for Ruwais piping package.',
    snapshot: {
      monthlyTotal: 33200,
      headcount: 4,
      positions: [
        { title: 'Welder', shift: 'Day', count: 4, monthlyBudget: 33200, costCenters: 'CC106 100%' },
      ],
    },
  },
  {
    id: 'rev-2-1',
    pcpId: 'pcp-2',
    revision: 1,
    author: 'Muhammad Imran',
    date: '2026-05-21',
    status: 'Approved',
    justification: 'Piping scope increased — 2 additional welders required per site mobilization plan.',
    summary: 'Rev. 1: Welder headcount increased 4 → 6; monthly cost +AED 16,600.',
    changes: [
      { field: 'Headcount', position: 'Welder', oldValue: '4', newValue: '6' },
      { field: 'Monthly Cost', position: 'Welder', oldValue: '33200', newValue: '49800' },
      { field: 'Priority', position: 'PCP Header', oldValue: 'Normal', newValue: 'Urgent' },
    ],
    snapshot: {
      monthlyTotal: 49800,
      headcount: 6,
      positions: [
        { title: 'Welder', shift: 'Day', count: 6, monthlyBudget: 49800, costCenters: 'CC106 100%' },
      ],
    },
  },
  {
    id: 'rev-3-0',
    pcpId: 'pcp-3',
    revision: 0,
    author: 'Muhammad Imran',
    date: '2026-05-10',
    status: 'Draft',
    summary: 'Draft: 1 Safety Officer for ADNOC Refinery Electrical Turnaround — Dubai site.',
    snapshot: {
      monthlyTotal: 11700,
      headcount: 1,
      positions: [
        { title: 'Safety Officer', shift: 'Day', count: 1, monthlyBudget: 11700, costCenters: 'CC305 100%' },
      ],
    },
  },
];

export const pcpInsights = {
  needs: [
    {
      id: 'need-1',
      title: 'Ruwais Piping & Welding Package – Piping phase starts Sep',
      description: 'Projected need: 14 Welders, 6 Riggers',
      recommendation: 'External Staffing Agency recommended',
      recommendationType: 'external',
      reasoning: 'Urgent timeline; in-house pool has 8 welder matches but only 2 riggers. Agency fill 17 days faster.',
      timeToFillInHouse: 38,
      timeToFillExternal: 21,
      inHouseMatches: 8,
    },
    {
      id: 'need-2',
      title: 'ADNOC Refinery Electrical Turnaround – Electrician vacancies ageing',
      description: '3 Electrician roles vacant 45+ days on night shift',
      recommendation: 'In-house pool – 2 matches available',
      recommendationType: 'inhouse',
      reasoning: 'Internal transfers from MEP – East can cover 2 roles within 14 days.',
      inHouseMatches: 2,
    },
  ],
  headcountForecast: {
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
    actual: [1180, 1195, 1205, 1210, 1220, 1240, null, null],
    projected: [null, null, null, null, null, 1240, 1275, 1310],
    confidenceLow: [null, null, null, null, null, 1240, 1250, 1270],
    confidenceHigh: [null, null, null, null, null, 1240, 1300, 1350],
  },
  costForecast: {
    months: ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    projected: [412000, 425000, 448000, 455000, 462000, 470000],
    budget: [420000, 420000, 430000, 430000, 440000, 440000],
    atRisk: [
      { costCenter: 'CC104', variance: 9, note: 'Projected 9% over budget by Sep' },
      { costCenter: 'CC106', variance: 6.2, note: 'Electrician night-shift premiums' },
    ],
  },
  weeklySummary: 'Vacant Electrician roles are ageing fastest on ADNOC Refinery Electrical Turnaround. Night-shift conversions added AED 14,000/month since Rev. 1 approvals. Recommend agency sourcing for 3 critical roles.',
};

export const executiveDashboard = {
  filters: {
    projects: ['All', 'ADNOC Refinery Electrical Turnaround', 'Ruwais Piping & Welding Package', 'Ruwais MEP Campus Build'],
    businessUnits: ['All', 'Construction – North', 'MEP – East', 'Logistics – South', 'Corporate HR'],
    costCenters: ['All', 'CC305', 'CC103', 'CC104', 'CC106', 'CC201'],
    geographies: ['All', 'Abu Dhabi', 'Ruwais', 'Dubai'],
    periods: ['This Month', 'This Quarter', 'YTD', 'Custom'],
  },
  headcount: { total: 1240, filled: 1082, vacant: 158, onHold: 12 },
  headcountByProject: [
    { project: 'ADNOC Refinery Electrical Turnaround', filled: 420, vacant: 58, businessUnit: 'Construction – North', geography: 'Abu Dhabi' },
    { project: 'Ruwais Piping & Welding Package', filled: 380, vacant: 62, businessUnit: 'Construction – North', geography: 'Ruwais' },
    { project: 'Ruwais MEP Campus Build', filled: 282, vacant: 38, businessUnit: 'MEP – East', geography: 'Ruwais' },
  ],
  budgetVsActual: [
    { costCenter: 'CC305', budget: 820000, actual: 785000, businessUnit: 'Construction – North', project: 'ADNOC Refinery Electrical Turnaround' },
    { costCenter: 'CC103', budget: 540000, actual: 562000, businessUnit: 'MEP – East', project: 'Ruwais MEP Campus Build' },
    { costCenter: 'CC104', budget: 310000, actual: 338000, businessUnit: 'Logistics – South', project: 'Ruwais Piping & Welding Package' },
    { costCenter: 'CC106', budget: 280000, actual: 297000, businessUnit: 'Construction – North', project: 'ADNOC Refinery Electrical Turnaround' },
  ],
  vacancyAgeing: [
    { trade: 'Electrician', d0_15: 2, d16_30: 3, d31_60: 5, d60plus: 4, businessUnit: 'Construction – North', geography: 'Abu Dhabi' },
    { trade: 'Welder', d0_15: 8, d16_30: 4, d31_60: 2, d60plus: 1, businessUnit: 'Construction – North', geography: 'Ruwais' },
    { trade: 'Rigger', d0_15: 3, d16_30: 2, d31_60: 1, d60plus: 0, businessUnit: 'Logistics – South', geography: 'Ruwais' },
  ],
  timeToFill: [
    { geography: 'Abu Dhabi', days: 24, businessUnit: 'Construction – North' },
    { geography: 'Ruwais', days: 31, businessUnit: 'Construction – North' },
    { geography: 'Dubai', days: 19, businessUnit: 'MEP – East' },
  ],
  chargingDistribution: [
    { name: 'ADNOC Refinery', value: 420000, businessUnit: 'Construction – North', project: 'ADNOC Refinery Electrical Turnaround' },
    { name: 'Ruwais Piping', value: 380000, businessUnit: 'Construction – North', project: 'Ruwais Piping & Welding Package' },
    { name: 'Ruwais MEP', value: 282000, businessUnit: 'MEP – East', project: 'Ruwais MEP Campus Build' },
    { name: 'Corporate Overhead', value: 158000, businessUnit: 'Corporate HR', project: 'All' },
  ],
  deploymentTimeline: [
    { role: 'Electrician', project: 'ADNOC Refinery', startMonth: 'Jan', endMonth: 'Aug', demob: false, businessUnit: 'Construction – North', geography: 'Abu Dhabi' },
    { role: 'Welder', project: 'Ruwais Piping', startMonth: 'Feb', endMonth: 'Oct', demob: false, businessUnit: 'Construction – North', geography: 'Ruwais' },
    { role: 'Site Engineer', project: 'Ruwais MEP', startMonth: 'Mar', endMonth: 'Jun', demob: true, businessUnit: 'MEP – East', geography: 'Ruwais' },
    { role: 'Rigger', project: 'Ruwais Piping', startMonth: 'Apr', endMonth: 'Dec', demob: false, businessUnit: 'Logistics – South', geography: 'Ruwais' },
  ],
  hiringSourceMix: [
    { source: 'In-house', count: 45, cost: 820000, businessUnit: 'Construction – North' },
    { source: 'Agency', count: 28, cost: 960000, businessUnit: 'Construction – North' },
    { source: 'Transfer', count: 12, cost: 340000, businessUnit: 'MEP – East' },
  ],
  nationalityBreakdown: [
    { nationality: 'Pakistani', value: 420 },
    { nationality: 'Indian', value: 310 },
    { nationality: 'Filipino', value: 180 },
    { nationality: 'Emirati', value: 95 },
    { nationality: 'Egyptian', value: 72 },
    { nationality: 'Bangladeshi', value: 68 },
    { nationality: 'Jordanian', value: 45 },
    { nationality: 'Other', value: 50 },
  ],
  approvalTat: { avgDays: 2.1, trend: -0.3 },
  approvalTatTrend: [
    { period: 'Jan', days: 2.8 },
    { period: 'Feb', days: 2.5 },
    { period: 'Mar', days: 2.4 },
    { period: 'Apr', days: 2.2 },
    { period: 'May', days: 2.1 },
    { period: 'Jun', days: 2.1 },
  ],
  alerts: [
    'CC104 projected 9% over budget by Sep',
    '5 Electrician vacancies aged 45+ days',
    '3 PCPs pending Finance approval (SLA < 24h)',
  ],
};
