export type SystemRole = 'Admin' | 'HR' | 'Department Manager' | 'Employee'

export type PcpRole = 'Requester' | 'Approver' | 'Admin' | 'Executive'

export interface DocumentRecord {
  id: string
  entityType: 'employee' | 'project'
  entityId: string
  title: string
  fileName: string
  mimeType: string
  size: number
  uploadedAt: string
}

export interface Employee {
  id: string
  employeeId: string
  fullName: string
  email: string
  department: string
  designation: string
  skills: string[]
  hourlyRate: number
  monthlySalary: number
  capacityHours: number
  availability: number
  status: 'Available' | 'Allocated' | 'Fully Allocated' | 'On Leave'
  utilization?: number
  allocatedHours?: number
  /** App access role */
  systemRole?: SystemRole
  /** PCP workflow role (optional) */
  pcpRole?: PcpRole | null
  businessUnit?: string
  managerId?: string | null
  active?: boolean
  onLeave?: boolean
  approvalDelegateId?: string | null
}

export interface PerformanceReview {
  id: string
  employeeId: string
  period: string
  rating: number
  goals: string
  notes: string
  reviewDate: string
  reviewerId: string
  reviewerName: string
  createdAt: string
}

export interface WorkAssignment {
  id: string
  employeeId: string
  title: string
  description: string
  projectId?: string | null
  startDate: string
  endDate?: string | null
  status: 'Active' | 'Completed' | 'Cancelled'
  assignedBy: string
  assignedByName: string
  createdAt: string
}

export interface Project {
  id: string
  projectId: string
  name: string
  client: string
  description: string
  projectManager: string
  projectManagerId?: string
  startDate: string
  endDate: string
  status: 'Draft' | 'Planned' | 'Active' | 'On Hold' | 'Completed' | 'Cancelled'
  budget: number
  revenue: number
  priority: string
  phases?: Phase[]
}

export interface Phase {
  id: string
  name: string
  milestones?: Milestone[]
}

export interface Milestone {
  id: string
  name: string
  dueDate?: string
}

export interface Task {
  id: string
  title: string
  description: string
  projectId: string
  phaseId?: string
  milestoneId?: string
  assigneeId?: string
  priority: string
  status: string
  kanbanStatus: string
  estimatedHours: number
  actualHours: number
  dueDate: string
  requiredSkills?: string[]
}

export interface Timesheet {
  id: string
  employeeId: string
  projectId: string
  taskId: string
  date: string
  hoursWorked: number
  notes: string
  status: 'Approved' | 'Rejected' | 'Pending'
}

export interface Budget {
  id: string
  projectId: string
  amount: number
  plannedCost: number
  actualCost: number
  currency: string
}

export interface Risk {
  id: string
  projectId: string
  risk: string
  probability: string
  impact: string
  mitigation: string
  owner: string
  status: string
}

export interface Issue {
  id: string
  projectId: string
  issue: string
  owner: string
  status: string
  resolution: string
  priority: string
}

export interface Leave {
  id: string
  employeeId: string
  type: string
  startDate: string
  endDate: string
  days: number
  status: string
  reason: string
}

export type AttendanceStatus = 'Present' | 'Absent' | 'Late' | 'Half Day' | 'On Leave'
export type AttendanceApprovalStatus = 'Pending' | 'Accepted'

export interface Attendance {
  id: string
  employeeId: string
  date: string
  checkIn?: string
  checkOut?: string
  status: AttendanceStatus
  workHours?: number
  location?: 'Site' | 'Office' | 'Remote'
  notes?: string
  autoGenerated?: boolean
  approvalStatus?: AttendanceApprovalStatus
  acceptedBy?: string
  acceptedAt?: string
  recordedBy?: string
  createdAt?: string
  updatedAt?: string
}

export interface Notification {
  id: string
  type: string
  title: string
  message: string
  userId: string
  read: boolean
  createdAt: string
}

export interface AuditLog {
  id: string
  action: string
  entity: string
  entityId: string
  details: string
  userId: string
  timestamp: string
}

export interface DashboardMetrics {
  kpis: {
    totalProjects: number
    activeProjects: number
    completedProjects: number
    totalEmployees: number
    availableResources: number
    allocatedResources: number
    budgetUtilization: number
    monthlyCost: number
    totalRevenue: number
    totalActualCost: number
    totalPlannedCost: number
    totalBudget: number
    profit: number
    profitMargin: number
    projectGrowthTrend?: number
    monthlyCostTrend?: number
    budgetUtilizationTrend?: number
  }
  projectStatusDistribution: { status: string; count: number }[]
  budgetVsActual: { name: string; budget: number; actual: number; planned: number }[]
  resourceUtilization: { id: string; name: string; department: string; utilization: number; allocatedHours: number; capacityHours: number }[]
  monthlySpending: { month: string; cost: number }[]
  taskProgress: { status: string; count: number }[]
  kanbanCounts: Record<string, number>
  projectProfitability: { projectId: string; projectName: string; budget: number; plannedCost: number; actualCost: number; remaining: number; consumption: number; health: string; revenue: number; profit: number; margin: number }[]
  employeeAllocation: { name: string; allocated: number; available: number }[]
}

export interface AssigneeSuggestion {
  employee: Employee
  skillMatch: number
  utilization: number
  availableHours: number
  score: number
  isBestMatch: boolean
  forecast: {
    capacityHours: number
    allocatedHours: number
    availableHours: number
    utilization: number
    warning: { level: string; message: string }
  }
}

export interface CapacityForecast {
  weekStart: string
  weekEnd: string
  capacityHours: number
  allocatedHours: number
  availableHours: number
  utilization: number
  warning: { level: string; message: string }
  assignedTasks: { id: string; title: string; hours: number }[]
}

export type PcpStatus = 'Draft' | 'In Approval' | 'Approved' | 'Rejected' | 'Returned' | 'Closed'

export interface PcpBenefit {
  name: string
  amount: number
}

export interface PcpCostCenterCharge {
  code: string
  percent: number
}

export interface PcpPosition {
  id?: string
  title: string
  jobFamily: string
  grade: string
  count: number
  employmentType: string
  shift: string
  workLocation: string
  plannedStart: string
  plannedDemob?: string
  reportingLine?: string
  marketSalary?: number
  proposedSalary: number
  salaryOnHired?: number | null
  benefits?: PcpBenefit[]
  contractDuration: string
  noticePeriod: string
  probationPeriod?: string
  costCenters: PcpCostCenterCharge[]
  bandBreachJustification?: string
  monthlyBudget?: number
  totalBudget?: number
  actualCost?: number | null
  filled?: number
  vacant?: number
  daysVacant?: number
}

export interface PcpApprovalStep {
  step: string
  by: string
  at?: string | null
  tatHours?: number | null
  slaDue?: string
}

export interface PcpRequest {
  id: string
  pcpNo: string
  client: string
  clientLocation: string
  recruitmentType: string
  issueDate: string
  requiredByDate: string
  businessUnit: string
  wbs: string
  priority: string
  requestedBy: string
  requestedById?: string
  status: PcpStatus
  currentStage: string
  revision: number
  slaHoursRemaining?: number
  slaOverdue?: boolean
  sapSync?: string
  approvalTrail: PcpApprovalStep[]
  positions: PcpPosition[]
  monthlyTotal?: number
  annualTotal?: number
  budgetVsActual?: number
  positionSummary?: string
  createdAt?: string
  updatedAt?: string
  revisions?: PcpRevision[]
}

export interface PcpRevisionSnapshotPosition {
  title: string
  shift?: string
  count?: number
  monthlyBudget?: number
  costCenters?: string
}

export interface PcpRevisionSnapshot {
  monthlyTotal?: number
  headcount?: number
  positions?: PcpRevisionSnapshotPosition[]
}

export interface PcpRevision {
  id: string
  pcpId: string
  revision: number
  author: string
  date: string
  status: string
  summary: string
  justification?: string
  changes?: { field: string; position: string; oldValue: string; newValue: string }[]
  snapshot?: PcpRevisionSnapshot
}

export interface PcpUser {
  id: string
  name: string
  email: string
  role: PcpRole
  businessUnit: string
  designation: string
  active: boolean
  onLeave?: boolean
  approvalDelegateId?: string | null
}

export interface PcpMasters {
  clients: string[]
  locations: string[]
  recruitmentTypes: string[]
  businessUnits: string[]
  wbsByBu: Record<string, string[]>
  priorities: string[]
  positionTitles: string[]
  jobFamilies: string[]
  grades: { code: string; bandMin: number; bandMax: number }[]
  employmentTypes: string[]
  shifts: string[]
  workLocations: string[]
  contractDurations: string[]
  noticePeriods: string[]
  probationPeriods: string[]
  benefits: string[]
  costCenters: { code: string; name: string }[]
  reportingLines: string[]
}
