import { useCallback, useEffect, useMemo, useState } from 'react'
import { Plus, Pencil, Trash2, CalendarCheck, UserCheck, UserX, Clock, LogIn, LogOut, CheckCircle2 } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select } from '@/components/ui/select'
import { Skeleton } from '@/components/ui/skeleton'
import { AttendanceFormDialog } from '@/components/forms/AttendanceFormDialog'
import { api } from '@/lib/api'
import { useEmployeeStore } from '@/stores/useEmployeeStore'
import { useAuthStore } from '@/stores/useAuthStore'
import { canManageAttendance } from '@/lib/roles'
import { useEffectiveRoles } from '@/lib/useEffectiveRoles'
import { cn, getStatusColor } from '@/lib/utils'
import type { Attendance } from '@/types'

const AUTO_ABSENT_AFTER = { hour: 10, minute: 30 }

function isWeekday(dateStr: string) {
  const day = new Date(`${dateStr}T12:00:00`).getDay()
  return day !== 0 && day !== 6
}

function canCheckInToday(todayRecord: Attendance | null, today: string) {
  if (!isWeekday(today)) return false
  if (todayRecord?.checkIn && !todayRecord.autoGenerated) return false
  if (todayRecord?.status === 'On Leave') return false
  return true
}

function canCheckOutToday(todayRecord: Attendance | null, today: string) {
  if (!isWeekday(today)) return false
  if (!todayRecord?.checkIn) return false
  if (todayRecord.checkOut) return false
  if (todayRecord.status === 'On Leave') return false
  return true
}

function canAcceptRecord(record: Attendance) {
  if (record.approvalStatus === 'Accepted') return false
  if (record.autoGenerated) return true
  if (record.status === 'Absent' || record.status === 'On Leave') return true
  return Boolean(record.checkOut)
}

function approvalLabel(status?: Attendance['approvalStatus']) {
  return status === 'Accepted' ? 'Accepted' : 'Pending'
}

function approvalColor(status?: Attendance['approvalStatus']) {
  return status === 'Accepted'
    ? 'bg-emerald-500/10 text-emerald-700'
    : 'bg-amber-500/10 text-amber-700'
}

function isBeforeAutoAbsentWindow() {
  const now = new Date()
  const mins = now.getHours() * 60 + now.getMinutes()
  return mins < AUTO_ABSENT_AFTER.hour * 60 + AUTO_ABSENT_AFTER.minute
}

export function AttendancePage() {
  const today = new Date().toISOString().slice(0, 10)
  const [records, setRecords] = useState<Attendance[]>([])
  const [todayRecord, setTodayRecord] = useState<Attendance | null>(null)
  const [loading, setLoading] = useState(true)
  const [checkInLoading, setCheckInLoading] = useState(false)
  const [checkOutLoading, setCheckOutLoading] = useState(false)
  const [checkInError, setCheckInError] = useState<string | null>(null)
  const [acceptingId, setAcceptingId] = useState<string | null>(null)
  const [filterApproval, setFilterApproval] = useState<'all' | 'pending' | 'accepted'>('all')
  const [checkInLocation, setCheckInLocation] = useState<'Site' | 'Office' | 'Remote'>('Site')
  const [filterDate, setFilterDate] = useState(today)
  const [filterStatus, setFilterStatus] = useState('all')
  const [search, setSearch] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [editing, setEditing] = useState<Attendance | null>(null)
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const { employees, fetchEmployees } = useEmployeeStore()
  const { user } = useAuthStore()
  const { systemRole, pcpRole } = useEffectiveRoles()
  const canManage = canManageAttendance(systemRole, pcpRole)

  const loadAdmin = useCallback(async (date: string) => {
    const data = await api.get<Attendance[]>(`/attendance?date=${date}&applyAutoAbsent=true`)
    setRecords(data.sort((a, b) => b.date.localeCompare(a.date) || a.employeeId.localeCompare(b.employeeId)))
  }, [])

  const loadSelf = useCallback(async () => {
    if (!user?.id) return
    const [{ record }, history] = await Promise.all([
      api.get<{ record: Attendance | null }>('/attendance/today'),
      api.get<Attendance[]>(`/attendance?employeeId=${user.id}`),
    ])
    setTodayRecord(record)
    setRecords(history.sort((a, b) => b.date.localeCompare(a.date)))
  }, [user?.id])

  const load = useCallback(async () => {
    if (canManage) {
      await loadAdmin(filterDate)
    } else {
      await loadSelf()
    }
    setLoading(false)
  }, [canManage, filterDate, loadAdmin, loadSelf])

  useEffect(() => {
    setLoading(true)
    Promise.all([load(), fetchEmployees()])
  }, [load, fetchEmployees])

  useEffect(() => {
    if (!canManage) return
    loadAdmin(filterDate)
  }, [canManage, filterDate, loadAdmin])

  const dayRecords = useMemo(
    () => (canManage ? records : records.filter((r) => r.date === today)),
    [records, filterDate, canManage, today],
  )

  const filtered = useMemo(() => {
    if (!canManage) {
      return records.slice(0, 14)
    }
    let list = filterDate ? records : records
    if (filterStatus !== 'all') list = list.filter((r) => r.status === filterStatus)
    if (filterApproval === 'pending') list = list.filter((r) => r.approvalStatus !== 'Accepted')
    if (filterApproval === 'accepted') list = list.filter((r) => r.approvalStatus === 'Accepted')
    if (search.trim()) {
      const q = search.toLowerCase()
      list = list.filter((r) => {
        const emp = employees.find((e) => e.id === r.employeeId)
        return emp?.fullName.toLowerCase().includes(q) || emp?.department.toLowerCase().includes(q)
      })
    }
    return list
  }, [records, filterDate, filterStatus, filterApproval, search, employees, canManage])

  const stats = useMemo(() => ({
    present: dayRecords.filter((r) => r.status === 'Present').length,
    absent: dayRecords.filter((r) => r.status === 'Absent').length,
    late: dayRecords.filter((r) => r.status === 'Late').length,
    onLeave: dayRecords.filter((r) => r.status === 'On Leave' || r.status === 'Half Day').length,
    pending: dayRecords.filter((r) => r.approvalStatus !== 'Accepted').length,
  }), [dayRecords])

  const handleCheckIn = async () => {
    setCheckInLoading(true)
    setCheckInError(null)
    try {
      const record = await api.post<Attendance>('/attendance/check-in', { location: checkInLocation })
      setTodayRecord(record)
      setRecords((prev) => {
        const rest = prev.filter((r) => r.id !== record.id && !(r.date === record.date && r.employeeId === record.employeeId))
        return [record, ...rest].sort((a, b) => b.date.localeCompare(a.date))
      })
    } catch (err) {
      setCheckInError(err instanceof Error ? err.message : 'Check-in failed')
    } finally {
      setCheckInLoading(false)
    }
  }

  const handleCheckOut = async () => {
    setCheckOutLoading(true)
    setCheckInError(null)
    try {
      const record = await api.post<Attendance>('/attendance/check-out', {})
      setTodayRecord(record)
      setRecords((prev) => {
        const rest = prev.filter((r) => r.id !== record.id)
        return [record, ...rest].sort((a, b) => b.date.localeCompare(a.date))
      })
    } catch (err) {
      setCheckInError(err instanceof Error ? err.message : 'Check-out failed')
    } finally {
      setCheckOutLoading(false)
    }
  }

  const handleAccept = async (id: string) => {
    setAcceptingId(id)
    try {
      const record = await api.post<Attendance>(`/attendance/${id}/accept`, {})
      setRecords((prev) => prev.map((r) => (r.id === id ? record : r)))
    } finally {
      setAcceptingId(null)
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this attendance record?')) return
    setDeletingId(id)
    try {
      await api.delete(`/attendance/${id}`)
      setRecords((prev) => prev.filter((r) => r.id !== id))
    } finally {
      setDeletingId(null)
    }
  }

  const openCreate = () => {
    setEditing(null)
    setFormOpen(true)
  }

  const openEdit = (record: Attendance) => {
    setEditing(record)
    setFormOpen(true)
  }

  const showCheckIn = canCheckInToday(todayRecord, today)
  const showCheckOut = canCheckOutToday(todayRecord, today)
  const pendingAbsent = !todayRecord && isWeekday(today) && isBeforeAutoAbsentWindow()

  if (loading) return <Skeleton className="h-96" />

  if (!canManage) {
    return (
      <div className="space-y-4 animate-fade-in min-w-0 sm:space-y-6">
        <div>
          <h1 className="text-xl font-bold sm:text-2xl">My Attendance</h1>
          <p className="text-sm text-muted-foreground">
            Check in and check out daily · HR/Admin must accept your attendance
          </p>
        </div>

        <Card className="border-primary/20">
          <CardHeader>
            <CardTitle className="text-lg">Today — {today}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {todayRecord ? (
              <div className="flex flex-wrap items-center gap-3">
                <span className={cn('rounded-full px-3 py-1 text-sm font-medium', getStatusColor(todayRecord.status))}>
                  {todayRecord.status}
                </span>
                {todayRecord.checkIn && (
                  <span className="text-sm text-muted-foreground">Checked in at {todayRecord.checkIn}</span>
                )}
                {todayRecord.checkOut && (
                  <span className="text-sm text-muted-foreground">· Checked out at {todayRecord.checkOut}</span>
                )}
                {todayRecord.workHours ? (
                  <span className="text-sm text-muted-foreground">· {todayRecord.workHours}h</span>
                ) : null}
                {todayRecord.location && (
                  <span className="text-sm text-muted-foreground">· {todayRecord.location}</span>
                )}
                <span className={cn('rounded-full px-2 py-0.5 text-xs font-medium', approvalColor(todayRecord.approvalStatus))}>
                  {approvalLabel(todayRecord.approvalStatus)}
                </span>
                {todayRecord.autoGenerated && todayRecord.status === 'Absent' && (
                  <span className="text-xs text-amber-600">Auto-marked absent (no check-in)</span>
                )}
              </div>
            ) : pendingAbsent ? (
              <p className="text-sm text-muted-foreground">
                You have not checked in yet. Mark attendance before 10:30 AM to avoid being marked absent.
              </p>
            ) : !isWeekday(today) ? (
              <p className="text-sm text-muted-foreground">Check-in is not required on weekends.</p>
            ) : (
              <p className="text-sm text-muted-foreground">No attendance recorded for today.</p>
            )}

            {(showCheckIn || showCheckOut) && (
              <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-end">
                {showCheckIn && (
                  <>
                    <div className="space-y-1">
                      <label className="text-xs font-medium text-muted-foreground">Location</label>
                      <Select
                        value={checkInLocation}
                        onChange={(e) => setCheckInLocation(e.target.value as typeof checkInLocation)}
                        className="w-full sm:w-40"
                      >
                        <option value="Site">Site</option>
                        <option value="Office">Office</option>
                        <option value="Remote">Remote</option>
                      </Select>
                    </div>
                    <Button onClick={handleCheckIn} disabled={checkInLoading}>
                      <LogIn className="h-4 w-4" />
                      {checkInLoading ? 'Checking in…' : todayRecord?.autoGenerated ? 'Check In (update)' : 'Check In'}
                    </Button>
                  </>
                )}
                {showCheckOut && (
                  <Button variant="outline" onClick={handleCheckOut} disabled={checkOutLoading}>
                    <LogOut className="h-4 w-4" />
                    {checkOutLoading ? 'Checking out…' : 'Check Out'}
                  </Button>
                )}
              </div>
            )}

            {checkInError && (
              <p className="text-sm text-destructive">{checkInError}</p>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Recent History</CardTitle></CardHeader>
          <CardContent className="table-scroll px-0 pt-0">
            <table className="w-full min-w-[480px] text-sm">
              <thead>
                <tr className="border-b text-left text-muted-foreground">
                  <th className="py-2 pl-4 pr-3 font-medium">Date</th>
                  <th className="py-2 pr-3 font-medium">Check-in</th>
                  <th className="py-2 pr-3 font-medium">Check-out</th>
                  <th className="py-2 pr-3 font-medium">Location</th>
                  <th className="py-2 pr-3 font-medium">Status</th>
                  <th className="py-2 pr-4 font-medium">Approval</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => (
                  <tr key={r.id} className="border-b border-border/50 hover:bg-muted/30">
                    <td className="py-3 pl-4 pr-3">{r.date}</td>
                    <td className="py-3 pr-3">{r.checkIn || '—'}</td>
                    <td className="py-3 pr-3">{r.checkOut || '—'}</td>
                    <td className="py-3 pr-3">{r.location || '—'}</td>
                    <td className="py-3 pr-3">
                      <span className={cn('rounded-full px-2 py-0.5 text-xs font-medium', getStatusColor(r.status))}>
                        {r.status}
                      </span>
                      {r.autoGenerated && (
                        <span className="ml-1 text-xs text-muted-foreground">(auto)</span>
                      )}
                    </td>
                    <td className="py-3 pr-4">
                      <span className={cn('rounded-full px-2 py-0.5 text-xs font-medium', approvalColor(r.approvalStatus))}>
                        {approvalLabel(r.approvalStatus)}
                      </span>
                    </td>
                  </tr>
                ))}
                {!filtered.length && (
                  <tr>
                    <td colSpan={6} className="py-8 text-center text-muted-foreground">
                      No attendance records yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-4 animate-fade-in min-w-0 sm:space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold sm:text-2xl">Attendance</h1>
          <p className="text-sm text-muted-foreground">
            Review and accept employee check-ins · {filterDate === today ? 'today' : filterDate}
          </p>
        </div>
        {canManage && (
          <Button onClick={openCreate}><Plus className="h-4 w-4" /> Mark Attendance</Button>
        )}
      </div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-5 sm:gap-4">
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <div className="rounded-lg bg-emerald-500/10 p-2 text-emerald-600"><UserCheck className="h-5 w-5" /></div>
            <div><p className="text-2xl font-bold">{stats.present}</p><p className="text-xs text-muted-foreground">Present</p></div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <div className="rounded-lg bg-red-500/10 p-2 text-red-600"><UserX className="h-5 w-5" /></div>
            <div><p className="text-2xl font-bold">{stats.absent}</p><p className="text-xs text-muted-foreground">Absent</p></div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <div className="rounded-lg bg-amber-500/10 p-2 text-amber-600"><Clock className="h-5 w-5" /></div>
            <div><p className="text-2xl font-bold">{stats.late}</p><p className="text-xs text-muted-foreground">Late</p></div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <div className="rounded-lg bg-orange-500/10 p-2 text-orange-600"><CalendarCheck className="h-5 w-5" /></div>
            <div><p className="text-2xl font-bold">{stats.onLeave}</p><p className="text-xs text-muted-foreground">Leave / Half day</p></div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <div className="rounded-lg bg-violet-500/10 p-2 text-violet-600"><CheckCircle2 className="h-5 w-5" /></div>
            <div><p className="text-2xl font-bold">{stats.pending}</p><p className="text-xs text-muted-foreground">Pending approval</p></div>
          </CardContent>
        </Card>
      </div>

      <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center">
        <Input type="date" value={filterDate} onChange={(e) => setFilterDate(e.target.value)} className="w-full sm:w-auto" />
        <Input
          placeholder="Search employee…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full sm:max-w-xs"
        />
        <div className="flex flex-wrap gap-2">
          {(['all', 'pending', 'accepted'] as const).map((f) => (
            <Button key={f} variant={filterApproval === f ? 'default' : 'outline'} size="sm" onClick={() => setFilterApproval(f)}>
              {f === 'all' ? 'All approvals' : f === 'pending' ? 'Pending' : 'Accepted'}
            </Button>
          ))}
        </div>
        <div className="flex flex-wrap gap-2">
          {['all', 'Present', 'Absent', 'Late', 'Half Day', 'On Leave'].map((f) => (
            <Button key={f} variant={filterStatus === f ? 'default' : 'outline'} size="sm" onClick={() => setFilterStatus(f)}>
              {f === 'all' ? 'All' : f}
            </Button>
          ))}
        </div>
      </div>

      <Card>
        <CardHeader><CardTitle>Attendance Records</CardTitle></CardHeader>
        <CardContent className="table-scroll px-0 pt-0">
          <table className="w-full min-w-[720px] text-sm">
            <thead>
              <tr className="border-b text-left text-muted-foreground">
                <th className="py-2 pl-4 pr-3 font-medium">Date</th>
                <th className="py-2 pr-3 font-medium">Employee</th>
                <th className="py-2 pr-3 font-medium">Check-in</th>
                <th className="py-2 pr-3 font-medium">Check-out</th>
                <th className="py-2 pr-3 font-medium">Hours</th>
                <th className="py-2 pr-3 font-medium">Location</th>
                <th className="py-2 pr-3 font-medium">Status</th>
                <th className="py-2 pr-3 font-medium">Approval</th>
                {canManage && <th className="py-2 pr-4 font-medium">Actions</th>}
              </tr>
            </thead>
            <tbody>
              {filtered.map((r) => {
                const emp = employees.find((e) => e.id === r.employeeId)
                return (
                  <tr key={r.id} className="border-b border-border/50 hover:bg-muted/30">
                    <td className="py-3 pl-4 pr-3">{r.date}</td>
                    <td className="py-3 pr-3">
                      <p className="font-medium">{emp?.fullName || '—'}</p>
                      <p className="text-xs text-muted-foreground">{emp?.department}</p>
                    </td>
                    <td className="py-3 pr-3">{r.checkIn || '—'}</td>
                    <td className="py-3 pr-3">{r.checkOut || '—'}</td>
                    <td className="py-3 pr-3">{r.workHours ? `${r.workHours}h` : '—'}</td>
                    <td className="py-3 pr-3">{r.location || '—'}</td>
                    <td className="py-3 pr-3">
                      <span className={cn('rounded-full px-2 py-0.5 text-xs font-medium', getStatusColor(r.status))}>{r.status}</span>
                      {r.autoGenerated && (
                        <span className="ml-1 text-xs text-muted-foreground">(auto)</span>
                      )}
                    </td>
                    <td className="py-3 pr-3">
                      <span className={cn('rounded-full px-2 py-0.5 text-xs font-medium', approvalColor(r.approvalStatus))}>
                        {approvalLabel(r.approvalStatus)}
                      </span>
                    </td>
                    {canManage && (
                      <td className="py-3 pr-4">
                        <div className="flex gap-1">
                          {canAcceptRecord(r) && (
                            <Button
                              size="sm"
                              variant="ghost"
                              className="action-icon-btn text-emerald-600"
                              disabled={acceptingId === r.id}
                              onClick={() => handleAccept(r.id)}
                              title="Accept attendance"
                            >
                              <CheckCircle2 />
                            </Button>
                          )}
                          <Button size="sm" variant="ghost" className="action-icon-btn" onClick={() => openEdit(r)}>
                            <Pencil />
                          </Button>
                          <Button
                            size="sm"
                            variant="ghost"
                            className="action-icon-btn text-destructive"
                            disabled={deletingId === r.id}
                            onClick={() => handleDelete(r.id)}
                          >
                            <Trash2 />
                          </Button>
                        </div>
                      </td>
                    )}
                  </tr>
                )
              })}
              {!filtered.length && (
                <tr>
                  <td colSpan={canManage ? 9 : 8} className="py-8 text-center text-muted-foreground">
                    No attendance records for this filter.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </CardContent>
      </Card>

      <AttendanceFormDialog
        open={formOpen}
        onClose={() => { setFormOpen(false); setEditing(null) }}
        onSaved={() => loadAdmin(filterDate)}
        employees={employees}
        attendance={editing}
        defaultDate={filterDate}
        recordedBy={user?.id}
      />
    </div>
  )
}
